### ISSUE TITLE
LCD not updating when rotating encoder for function select

### ISSUE THREAD

**Issue by UaNotJosh** [Herring-UGAECSE-2920/Class-Instructions#24]
Hey guys, 
So I have been working on the UI for our project and I was messing with the function select option and for some reason, the LCD just does not update on a certain option in either direction when rotating through the options. When rotating downwards, it skips the circle function and when rotating upwards it skips the quadratic function. I have attached the relevant code clip in the downwards callback. The upwards callback is the exact same except the order is reverse so that the list is consistent. I added the time.sleeps in case it was an issue with updating the values too quickly or just for experimentation to explore possible solutions, but commented them out after they did not help. I have also attached a while loop that is at the bottom of our code to constantly update the LCD with the needed values which is what the printed variable is used for. I hope I gave enough information for your help. Please just let me know of anything else that is needed. Thanks in advance guys!
![image](https://user-images.githubusercontent.com/72629679/111931906-a8fddd80-8a92-11eb-92de-e4ae1f05012b.png)
![image](https://user-images.githubusercontent.com/72629679/111932073-0a25b100-8a93-11eb-993b-78f3d2df8d9f.png)

**Comment by ktkoffroth** [comment]
My only thoughts are that the function is being called twice when you think it is being called once. I don't really see anything in particular wrong with your code, but I can't really help you debug unless I dive into your codebase and got familiar with it. These kinds of issues are ones you all have to work out on your own, since each implementation of the design is different, I can't be the debugger for everyone.
